### ISSUE TITLE
[suggestion] Get a '3 way' fridge

### ISSUE THREAD

**Issue by symroe** [andylolz/boat#10]
Suggest one of these, linked up to gas.  They hardly use any gas and work really well (and are east to service):

http://www.ebay.co.uk/sch/i.html?_from=R40&_sacat=0&_nkw=3+way+frigde&_blrs=spell_check

**Comment by andylolz** [comment]
We decided against this… Basically because gas is a premium (in part due to #4) and we have loads of solar now.
