### ISSUE TITLE
Real time GPS location, published on the internet

### ISSUE THREAD

**Issue by symroe** [andylolz/boat#11]
So your friends can find you easier.

**Comment by andylolz** [comment]
+1 this is a necessary feature. I am sure @Madsybaby agrees.

**Comment by andylolz** [comment]
I am still keen to do this!

**Comment by sndrsk** [comment]
If you have an amateur radio license, you can do this with initial startup costs but no subscription fees. https://en.wikipedia.org/wiki/Automatic_Packet_Reporting_System

**Comment by andylolz** [comment]
Well I have GPS on my phone & watch, so would rather use that.

Gonna use this to start with, since we currently log cruising pattern there already:
https://calendar.google.com/calendar/ical/7phgh51gv2gnm4jqigj8qaf06g%40group.calendar.google.com/private-684722edc06482cf6c23aab108ca192d/basic.ics

**Comment by andylolz** [comment]
This more or less works: http://andylolz.github.io/boat/

It’s a bit of a mess, because it uses data scraped from the gcal (simply to avoid using the google calendar API).

**Comment by symroe** [comment]
`CNAME wheredoiboat.co.uk`
