### ISSUE TITLE
Replace all buffalo boards

### ISSUE THREAD

**Issue by andylolz** [andylolz/boat#12]
The wooden lid for the gas locker is cracked, so lets water in when it rains. We need to chop up some marine ply and make a new one!

**Comment by andylolz** [comment]
@Madsybaby thinks this is fixed now (simply by putting the lid on the other way around!) I remain sceptical.

**Comment by andylolz** [comment]
Can’t remember if I mentioned, @Madsybaby, but Seb sounded keen to at least do the engine cover buffalo board.

**Comment by Madsybaby** [comment]
No you didnt but I think we should @andylolz. What;s there will look very
sad once it's all shiny and new.

**Comment by andylolz** [comment]
> What;s there will look very sad once it's all shiny and new.

True fact
