### ISSUE TITLE
Bolt on chimney hat

### ISSUE THREAD

**Issue by andylolz** [andylolz/boat#26]
We’ve got a lovely new chimney, but the hat is at risk of blowing away. It needs bolting in place 🔩

**Comment by andylolz** [comment]
Honestly, I can’t remember where I put it.

**Comment by Madsybaby** [comment]
I put it back on you bugger! It's on there ... 

Excuse brevity sent from an iPhone ...

**Comment by andylolz** [comment]
Chimney hat blew away :(
