### ISSUE TITLE
Paint outside!

### ISSUE THREAD

**Issue by andylolz** [andylolz/boat#30]
LSC are painting the boat! But what colour??? ⛵️

**Comment by JoeMitchell** [comment]
Just going to leave the demo club colours here: 

#333333 Grey
#E6007E Pink
#FFFFFF White
#00AEEF Electric Blue
#48BC25 Pea Green

**Comment by JoeMitchell** [comment]
And also https://docs.google.com/spreadsheets/d/161Df7tQFZrKhVPAy4vCT19RoDXl2dAsqOWRdOkNInp4/edit#gid=0.

Just in case.

**Comment by JoeMitchell** [comment]
Also please rename the boat Floaty McVoteplace and offer it as a polling station at every election.

**Comment by andylolz** [comment]
We also need to choose a logo design:
https://d26dzxoao6i3hh.cloudfront.net/items/3S3x0g0y0b3g0S0R2j0x/jasmine-stage5.pdf

**Comment by andylolz** [comment]
#itshappening 
![20170620_074426](https://user-images.githubusercontent.com/464193/27335929-fd4de958-55c5-11e7-9886-3de6f6eaffa0.jpg)
![20170620_074439](https://user-images.githubusercontent.com/464193/27335930-fd527c2a-55c5-11e7-9e13-6b1b4d25bea6.jpg)

**Comment by JoeMitchell** [comment]
I like it — the 'ruined paintwork' effect...

**Comment by Madsybaby** [comment]
Maybe that solves our colour conundrum ... just stick with the distressed
look.

**Comment by Madsybaby** [comment]
From Seb ... "Julian, the sign writer, says it will cost approximately £450
for the two sides." Didnt ask about HOW he'd do it. Let's chat / do more
research before we go back to him on it.

**Comment by robzor** [comment]
Surely it doesn't matter as the entire roof will be covered in high efficiency solar panels?

**Comment by andylolz** [comment]
Gotta paint the whole flippin thing, Rob

**Comment by robzor** [comment]
What, you aren't going to solar panel the sides and the underneath (especially the underneath)?

**Comment by andylolz** [comment]
Please end this

**Comment by andylolz** [comment]
I will destroy you

**Comment by andylolz** [comment]
:tada: :tada: :tada: :tada: It’s DONE :tada: :tada: :tada: :tada:
