### ISSUE TITLE
Buy new (rope?) fenders

### ISSUE THREAD

**Issue by andylolz** [andylolz/boat#32]
We’ve taken all the tyre fenders off (so no nesting birds this summer!)

We could put them back on after painting… but it might be nicer to get some lovely rope ones like the beautiful one @davewhiteland made!

**Comment by davewhiteland** [comment]
[piece of cake](http://www.instructables.com/id/Boat-Fender-DIY/) yarrrrrr

**Comment by davewhiteland** [comment]
Er actually it was bloody hard work iirc. I did mine (at the lovely [Weald and Downland Museum](http://www.wealddown.co.uk)) under the direction of Charlie Tyrell but I can't find him online at the moment.

**Comment by Madsybaby** [comment]
i might buy some of these as back up ... ;-)

http://www.blackpigfenders.co.uk/rope-side-fenders-14-c.asp

**Comment by andylolz** [comment]
@Madsybaby got some (budget ones)! Now we just need some really thin rope to tie them on.
