### ISSUE TITLE
We also got a dog...

### ISSUE THREAD

**Issue by terrortylor** [andylolz/boat#35]
In response to [https://github.com/andylolz/boat/issues/29](url)

![img_20170902_111445](https://user-images.githubusercontent.com/1199053/29997089-7f4abbcc-9002-11e7-8c00-8e6555270a61.jpg)

**Comment by andylolz** [comment]
We ❤️  Betty!!!!!!111

**Comment by andylolz** [comment]
Closing, but feel free to post more puppy pics @terrortylor!!! :heart: :heart: :heart:
