### ISSUE TITLE
Increase gas locker capacity

### ISSUE THREAD

**Issue by andylolz** [andylolz/boat#4]
Currently we can fit a max of ~~2*3.9kg~~ **4*3.9kg** propane cylinders in our gas locker. That’s okay… But if we were to start using the gas central heating, we’d run out of gas really fast.

It would be cool (if possible) to expand the gas locker down into the engine bay, so we could put bigger propane cylinders in.

**Comment by symroe** [comment]
I think you should just shove them at the front of the boat, and run new pipes along through the bedroom.  Loads more space at the front.

(plus, get a gas fridge before summer! – see #10)

**Comment by andylolz** [comment]
The empties live at the front at the moment, it’s a bit untidy… (But then the front is a big mess at the moment anyway).

Also, according to gas safety regulation they’re supposed to be in a locker.

**Comment by andylolz** [comment]
We’ve talked to a couple of metal workers about this, and it turns out the cheapest thing to do would be to expand the gas locker up instead of down (down turns out to be very expensive). So we’re not going to do this.

We manage fine with 4*3.9kg. It’s a bit more expensive, but it would take a lot of years before expanding the gas locker paid for itself.
