### ISSUE TITLE
Blacking / Survey / New rudder

### ISSUE THREAD

**Issue by Madsybaby** [andylolz/boat#8]
Reblack
Resurvey
Make rudder bigger!

**Comment by andylolz** [comment]
And rename! #6 is dependent on this!

**Comment by andylolz** [comment]
@Madsybaby: So… Where can we do this? It’s either St Pancras Basin or Enfield, right?

We could do either of those I guess. Maybe we should call both, then map out where we’re likely to be by the time we get the slot?

**Comment by Madsybaby** [comment]
@andylolz Yeah - sounds like a plan. We book the slot to take out the water, then we need to find people to do the work for that time. So bit of a juggle.

**Comment by andylolz** [comment]
Closing because this is done! Booked in at St Pancras dry dock.

**Comment by Madsybaby** [comment]
Still need to confirm with them a surveyor and the rudder extension ...
need to check whether we have to book a surveyor or whether they have one
they use / recommend ... x
